package model;
// Generated Aug 22, 2016 2:10:35 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DishHistory generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dish_history")
public class DishHistory implements java.io.Serializable {

	private Integer dishHistoryId;
	private Dish dish;
	private History history;

	public DishHistory() {
	}

	public DishHistory(Dish dish, History history) {
		this.dish = dish;
		this.history = history;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "dish_history_id", unique = true, nullable = false)
	public Integer getDishHistoryId() {
		return this.dishHistoryId;
	}

	public void setDishHistoryId(Integer dishHistoryId) {
		this.dishHistoryId = dishHistoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dish_id", nullable = false)
	public Dish getDish() {
		return this.dish;
	}

	public void setDish(Dish dish) {
		this.dish = dish;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "history_id", nullable = false)
	public History getHistory() {
		return this.history;
	}

	public void setHistory(History history) {
		this.history = history;
	}

}
