package model;
// Generated Aug 21, 2016 5:21:33 PM by Hibernate Tools 4.3.4.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Dish generated by hbm2java
 */
@Entity
@Table(name = "dish", catalog = "wecook", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Dish implements java.io.Serializable {

	private Integer id;
	private Cuisine cuisine;
	private Recipe recipe;
	private User user;
	private String name;
	private Long cost;
	private Date created;
	private Integer difficulty;
	private Date lastused;
	private Integer servings;
	private Integer time;
	private Integer spicy;
	private Integer burners;
	private Integer oven;
	private Integer count;
	private int public_;
	private Set<DishHistory> dishHistories = new HashSet<DishHistory>(0);

	public Dish() {
	}

	public Dish(Recipe recipe, String name, Date created, Date lastused, int public_) {
		this.recipe = recipe;
		this.name = name;
		this.created = created;
		this.lastused = lastused;
		this.public_ = public_;
	}

	public Dish(Cuisine cuisine, Recipe recipe, User user, String name, Long cost, Date created, Integer difficulty,
			Date lastused, Integer servings, Integer time, Integer spicy, Integer burners, Integer oven, Integer count,
			int public_, Set<DishHistory> dishHistories) {
		this.cuisine = cuisine;
		this.recipe = recipe;
		this.user = user;
		this.name = name;
		this.cost = cost;
		this.created = created;
		this.difficulty = difficulty;
		this.lastused = lastused;
		this.servings = servings;
		this.time = time;
		this.spicy = spicy;
		this.burners = burners;
		this.oven = oven;
		this.count = count;
		this.public_ = public_;
		this.dishHistories = dishHistories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cuisine")
	public Cuisine getCuisine() {
		return this.cuisine;
	}

	public void setCuisine(Cuisine cuisine) {
		this.cuisine = cuisine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "recipe", nullable = false)
	public Recipe getRecipe() {
		return this.recipe;
	}

	public void setRecipe(Recipe recipe) {
		this.recipe = recipe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "name", unique = true, nullable = false, length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "cost")
	public Long getCost() {
		return this.cost;
	}

	public void setCost(Long cost) {
		this.cost = cost;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "difficulty")
	public Integer getDifficulty() {
		return this.difficulty;
	}

	public void setDifficulty(Integer difficulty) {
		this.difficulty = difficulty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastused", nullable = false, length = 19)
	public Date getLastused() {
		return this.lastused;
	}

	public void setLastused(Date lastused) {
		this.lastused = lastused;
	}

	@Column(name = "servings")
	public Integer getServings() {
		return this.servings;
	}

	public void setServings(Integer servings) {
		this.servings = servings;
	}

	@Column(name = "time")
	public Integer getTime() {
		return this.time;
	}

	public void setTime(Integer time) {
		this.time = time;
	}

	@Column(name = "spicy")
	public Integer getSpicy() {
		return this.spicy;
	}

	public void setSpicy(Integer spicy) {
		this.spicy = spicy;
	}

	@Column(name = "burners")
	public Integer getBurners() {
		return this.burners;
	}

	public void setBurners(Integer burners) {
		this.burners = burners;
	}

	@Column(name = "oven")
	public Integer getOven() {
		return this.oven;
	}

	public void setOven(Integer oven) {
		this.oven = oven;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "public", nullable = false)
	public int getPublic_() {
		return this.public_;
	}

	public void setPublic_(int public_) {
		this.public_ = public_;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dish")
	public Set<DishHistory> getDishHistories() {
		return this.dishHistories;
	}

	public void setDishHistories(Set<DishHistory> dishHistories) {
		this.dishHistories = dishHistories;
	}

}
