package model;
// Generated Aug 22, 2016 2:10:35 PM by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Recipe generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "recipe", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Recipe implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Set<RecipeStepIngredient> recipeStepIngredients = new HashSet<RecipeStepIngredient>(0);
	private Set<RecipeStep> recipeSteps = new HashSet<RecipeStep>(0);
	private Set<Dish> dishes = new HashSet<Dish>(0);

	public Recipe() {
	}

	public Recipe(String name) {
		this.name = name;
	}

	public Recipe(String name, String description, Set<RecipeStepIngredient> recipeStepIngredients,
			Set<RecipeStep> recipeSteps, Set<Dish> dishes) {
		this.name = name;
		this.description = description;
		this.recipeStepIngredients = recipeStepIngredients;
		this.recipeSteps = recipeSteps;
		this.dishes = dishes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recipe")
	public Set<RecipeStepIngredient> getRecipeStepIngredients() {
		return this.recipeStepIngredients;
	}

	public void setRecipeStepIngredients(Set<RecipeStepIngredient> recipeStepIngredients) {
		this.recipeStepIngredients = recipeStepIngredients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recipe")
	public Set<RecipeStep> getRecipeSteps() {
		return this.recipeSteps;
	}

	public void setRecipeSteps(Set<RecipeStep> recipeSteps) {
		this.recipeSteps = recipeSteps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recipe")
	public Set<Dish> getDishes() {
		return this.dishes;
	}

	public void setDishes(Set<Dish> dishes) {
		this.dishes = dishes;
	}

}
