package model;
// Generated Aug 21, 2016 5:21:33 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RecipeStepIngredientId generated by hbm2java
 */
@Embeddable
public class RecipeStepIngredientId implements java.io.Serializable {

	private int ingredientId;
	private int unit;
	private long quantity;
	private int recipeStepId;
	private int recipeId;

	public RecipeStepIngredientId() {
	}

	public RecipeStepIngredientId(int ingredientId, int unit, long quantity, int recipeStepId, int recipeId) {
		this.ingredientId = ingredientId;
		this.unit = unit;
		this.quantity = quantity;
		this.recipeStepId = recipeStepId;
		this.recipeId = recipeId;
	}

	@Column(name = "ingredient_id", nullable = false)
	public int getIngredientId() {
		return this.ingredientId;
	}

	public void setIngredientId(int ingredientId) {
		this.ingredientId = ingredientId;
	}

	@Column(name = "unit", nullable = false)
	public int getUnit() {
		return this.unit;
	}

	public void setUnit(int unit) {
		this.unit = unit;
	}

	@Column(name = "quantity", nullable = false, precision = 10, scale = 0)
	public long getQuantity() {
		return this.quantity;
	}

	public void setQuantity(long quantity) {
		this.quantity = quantity;
	}

	@Column(name = "recipe_step_id", nullable = false)
	public int getRecipeStepId() {
		return this.recipeStepId;
	}

	public void setRecipeStepId(int recipeStepId) {
		this.recipeStepId = recipeStepId;
	}

	@Column(name = "recipe_id", nullable = false)
	public int getRecipeId() {
		return this.recipeId;
	}

	public void setRecipeId(int recipeId) {
		this.recipeId = recipeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecipeStepIngredientId))
			return false;
		RecipeStepIngredientId castOther = (RecipeStepIngredientId) other;

		return (this.getIngredientId() == castOther.getIngredientId()) && (this.getUnit() == castOther.getUnit())
				&& (this.getQuantity() == castOther.getQuantity())
				&& (this.getRecipeStepId() == castOther.getRecipeStepId())
				&& (this.getRecipeId() == castOther.getRecipeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIngredientId();
		result = 37 * result + this.getUnit();
		result = 37 * result + (int) this.getQuantity();
		result = 37 * result + this.getRecipeStepId();
		result = 37 * result + this.getRecipeId();
		return result;
	}

}
