package model;
// Generated Aug 21, 2016 5:21:33 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RecipeStepIngredient generated by hbm2java
 */
@Entity
@Table(name = "recipe_step_ingredient", catalog = "wecook")
public class RecipeStepIngredient implements java.io.Serializable {

	private RecipeStepIngredientId id;
	private Ingredient ingredient;
	private Recipe recipe;
	private RecipeStep recipeStep;
	private Unit unit;

	public RecipeStepIngredient() {
	}

	public RecipeStepIngredient(RecipeStepIngredientId id, Ingredient ingredient, Recipe recipe, RecipeStep recipeStep,
			Unit unit) {
		this.id = id;
		this.ingredient = ingredient;
		this.recipe = recipe;
		this.recipeStep = recipeStep;
		this.unit = unit;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ingredientId", column = @Column(name = "ingredient_id", nullable = false)),
			@AttributeOverride(name = "unit", column = @Column(name = "unit", nullable = false)),
			@AttributeOverride(name = "quantity", column = @Column(name = "quantity", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "recipeStepId", column = @Column(name = "recipe_step_id", nullable = false)),
			@AttributeOverride(name = "recipeId", column = @Column(name = "recipe_id", nullable = false)) })
	public RecipeStepIngredientId getId() {
		return this.id;
	}

	public void setId(RecipeStepIngredientId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ingredient_id", nullable = false, insertable = false, updatable = false)
	public Ingredient getIngredient() {
		return this.ingredient;
	}

	public void setIngredient(Ingredient ingredient) {
		this.ingredient = ingredient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "recipe_id", nullable = false, insertable = false, updatable = false)
	public Recipe getRecipe() {
		return this.recipe;
	}

	public void setRecipe(Recipe recipe) {
		this.recipe = recipe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "recipe_step_id", nullable = false, insertable = false, updatable = false)
	public RecipeStep getRecipeStep() {
		return this.recipeStep;
	}

	public void setRecipeStep(RecipeStep recipeStep) {
		this.recipeStep = recipeStep;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unit", nullable = false, insertable = false, updatable = false)
	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

}
