package model;
// Generated Aug 22, 2016 2:10:35 PM by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RecipeStep generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "recipe_step")
public class RecipeStep implements java.io.Serializable {

	private Integer recipeStepId;
	private Recipe recipe;
	private int stepNumber;
	private String instructions;
	private Set<RecipeStepIngredient> recipeStepIngredients = new HashSet<RecipeStepIngredient>(0);

	public RecipeStep() {
	}

	public RecipeStep(Recipe recipe, int stepNumber, String instructions) {
		this.recipe = recipe;
		this.stepNumber = stepNumber;
		this.instructions = instructions;
	}

	public RecipeStep(Recipe recipe, int stepNumber, String instructions,
			Set<RecipeStepIngredient> recipeStepIngredients) {
		this.recipe = recipe;
		this.stepNumber = stepNumber;
		this.instructions = instructions;
		this.recipeStepIngredients = recipeStepIngredients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recipe_step_id", unique = true, nullable = false)
	public Integer getRecipeStepId() {
		return this.recipeStepId;
	}

	public void setRecipeStepId(Integer recipeStepId) {
		this.recipeStepId = recipeStepId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "recipe_id", nullable = false)
	public Recipe getRecipe() {
		return this.recipe;
	}

	public void setRecipe(Recipe recipe) {
		this.recipe = recipe;
	}

	@Column(name = "step_number", nullable = false)
	public int getStepNumber() {
		return this.stepNumber;
	}

	public void setStepNumber(int stepNumber) {
		this.stepNumber = stepNumber;
	}

	@Column(name = "instructions", nullable = false, length = 600)
	public String getInstructions() {
		return this.instructions;
	}

	public void setInstructions(String instructions) {
		this.instructions = instructions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recipeStep")
	public Set<RecipeStepIngredient> getRecipeStepIngredients() {
		return this.recipeStepIngredients;
	}

	public void setRecipeStepIngredients(Set<RecipeStepIngredient> recipeStepIngredients) {
		this.recipeStepIngredients = recipeStepIngredients;
	}

}
