package model;
// Generated Jan 29, 2017 8:12:55 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TweetLog generated by hbm2java
 */
@Entity
@Table(name = "tweet_log", schema = "public")
public class TweetLog implements java.io.Serializable {

	private int tweetId;
	private String tweet;
	private Date tweetDate;
	private String handle;
	private Boolean processed;
	private Integer categoryId;
	private Date categorizeTime;
	private Integer categorizeUser;

	public TweetLog() {
	}

	public TweetLog(int tweetId, String tweet, Date tweetDate, String handle) {
		this.tweetId = tweetId;
		this.tweet = tweet;
		this.tweetDate = tweetDate;
		this.handle = handle;
	}

	public TweetLog(int tweetId, String tweet, Date tweetDate, String handle, Boolean processed, Integer categoryId,
			Date categorizeTime, Integer categorizeUser) {
		this.tweetId = tweetId;
		this.tweet = tweet;
		this.tweetDate = tweetDate;
		this.handle = handle;
		this.processed = processed;
		this.categoryId = categoryId;
		this.categorizeTime = categorizeTime;
		this.categorizeUser = categorizeUser;
	}

	@Id

	@Column(name = "tweet_id", unique = true, nullable = false)
	public int getTweetId() {
		return this.tweetId;
	}

	public void setTweetId(int tweetId) {
		this.tweetId = tweetId;
	}

	@Column(name = "tweet", nullable = false)
	public String getTweet() {
		return this.tweet;
	}

	public void setTweet(String tweet) {
		this.tweet = tweet;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tweet_date", nullable = false, length = 35)
	public Date getTweetDate() {
		return this.tweetDate;
	}

	public void setTweetDate(Date tweetDate) {
		this.tweetDate = tweetDate;
	}

	@Column(name = "handle", nullable = false, length = 40)
	public String getHandle() {
		return this.handle;
	}

	public void setHandle(String handle) {
		this.handle = handle;
	}

	@Column(name = "processed")
	public Boolean getProcessed() {
		return this.processed;
	}

	public void setProcessed(Boolean processed) {
		this.processed = processed;
	}

	@Column(name = "category_id")
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "categorize_time", length = 35)
	public Date getCategorizeTime() {
		return this.categorizeTime;
	}

	public void setCategorizeTime(Date categorizeTime) {
		this.categorizeTime = categorizeTime;
	}

	@Column(name = "categorize_user")
	public Integer getCategorizeUser() {
		return this.categorizeUser;
	}

	public void setCategorizeUser(Integer categorizeUser) {
		this.categorizeUser = categorizeUser;
	}

}
