package model;
// Generated Aug 28, 2016 2:18:37 PM by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserGroup generated by hbm2java
 */
@Entity
@Table(name = "user_group", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class UserGroup implements java.io.Serializable {

	private Integer groupId;
	private String name;
	private Set<User> users = new HashSet<User>(0);

	public UserGroup() {
	}

	public UserGroup(String name) {
		this.name = name;
	}

	public UserGroup(String name, Set<User> users) {
		this.name = name;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "group_id", unique = true, nullable = false)
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userGroup")
//	public Set<User> getUsers() {
//		return this.users;
//	}
//
//	public void setUsers(Set<User> users) {
//		this.users = users;
//	}

}
